"""empty message

Revision ID: 9cbf6ad033c7
Revises: 
Create Date: 2022-07-11 10:00:36.235057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cbf6ad033c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BookEdition',
    sa.Column('isbn', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('isbn')
    )
    op.create_table('Test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data1', sa.String(), nullable=True),
    sa.Column('data2', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('BookCopy',
    sa.Column('book_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('isbn', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['isbn'], ['BookEdition.isbn'], ),
    sa.PrimaryKeyConstraint('book_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('BookCopy')
    op.drop_table('Test')
    op.drop_table('BookEdition')
    # ### end Alembic commands ###
